spring.application.name=log-parser-service
server.port=8080

# Kafka
spring.kafka.bootstrap-servers=localhost:9092

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/logdb
spring.datasource.username=admin
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

# Embedding microservice
embedding.api-url=http://localhost:3000/embed

# Gemini
gemini.api-key=${GEMINI_API_KEY}
gemini.api-url=https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent

# Query settings
log.query.top-k=15